return {
  -- {
  --   'github/copilot.vim',
  --   lazy = false,
  --   enabled = true,
  --   config = function()
  --       --vim.g.copilot_no_tab_map = true
  --       vim.g.copilot_assume_mapped = true
  --       vim.g.copilot_tab_fallback = ""
  --       vim.api.nvim_set_keymap("i", "<C-J>", 'copilot#Accept("<CR>")', { silent = true, expr = true })
  --   end
  -- },
  -- You can also add new plugins here as well:
  -- Add plugins, the lazy syntax
  -- "andweeb/presence.nvim",
  -- {
  --   "ray-x/lsp_signature.nvim",
  --   event = "BufRead",
  --   config = function()
  --     require("lsp_signature").setup()
  --   end,
  -- },
}
